name: CI-CD

on:
    push:
        branches:
        - main
        - develop

env:
  NODE_VERSION: 16
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  linting:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn lint

  deploy:
    name: Fly Deploy
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
